# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:13
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"
    networks:
      - app-network

  gophkeeper:
    build:
      context: .
      dockerfile: Dockerfile  # Или укажите путь к Dockerfile, если он в другой папке
    ports:
      - "8081:8081"  # Замените на порт, который использует ваше приложение
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DATABASE_DSN: postgres://admin:admin@db:5432/db
      GRPC_ADDR: :8081

networks:
  app-network:
    driver: bridge