name: Build Go Binaries

on:
  release:
    types: [ created ]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, arm64 ]
        exclude:
          - goarch: arm64
            goos: windows
          - goarch: arm64
            goos: linux
    steps:
      - name: Get Release Info
        run: |
          echo "COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "VERSION=$(git describe --tags --abbrev=0 || echo 'v0.0.0')" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.51
        with:
          github_token: ${{ secrets.UPLOAD_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: |
            -X "main.buildVersion=${{ env.VERSION }}" 
            -X "main.buildCommit=${{ env.COMMIT }}"
            -X "main.buildDate=${{ env.BUILD_DATE }}"
          project_path: cmd/client
          asset_name: "GophKeeperClient-${{ env.RELEASE_TAG }}-${{ matrix.goos }}-${{ matrix.goarch }}"
          md5sum: false
